default_settings:
  INSTANCES: 10
  TIME_GAP_IN_INSTANCES: 30
  DEV_MODE: true
  HIT_GET_API: false
  BRIGHT_PROXIES: true
  HEADLESS: true

network:
  admob:
    DEV_GET_API: ""
    DEV_UPLOAD_API: ""
    DEV_INSERT_API: ""
